name: flutter_starter_template
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.4.4
  go_router: ^12.0.0
  fpdart: ^1.1.0
  dio: ^5.3.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.2.1
  path_provider: ^2.1.1
  hive: ^2.2.3
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  freezed: ^2.4.5

  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  riverpod_generator: ^2.3.5
  riverpod_lint: ^2.3.2
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    # - images/a_dot_burr.jpeg
    # - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: PlaypenSans
      fonts:
        - asset: assets/fonts/PlaypenSans-Regular.ttf
        - asset: assets/fonts/PlaypenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/PlaypenSans-SemiBold.ttf
          weight: 400
